#!/usr/bin/env python3

from flask import Flask, send_from_directory
import os

app = Flask(__name__)

@app.route('/', defaults={'path': 'index.html'})
@app.route('/<path:path>')
def serve_file(path):
    return send_from_directory(os.getcwd(), path)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=443, ssl_context=('/etc/letsencrypt/live/tempusvalorem.net/fullchain.pem', '/etc/letsencrypt/live/tempusvalorem.net/privkey.pem'))
